/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ohk1hc_calculatorgui_Calculator */

#ifndef _Included_com_example_ohk1hc_calculatorgui_Calculator
#define _Included_com_example_ohk1hc_calculatorgui_Calculator
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ohk1hc_calculatorgui_Calculator_SUMMATION
#define com_example_ohk1hc_calculatorgui_Calculator_SUMMATION 0L
#undef com_example_ohk1hc_calculatorgui_Calculator_SUBTRACTION
#define com_example_ohk1hc_calculatorgui_Calculator_SUBTRACTION 1L
#undef com_example_ohk1hc_calculatorgui_Calculator_MULTIPLICATION
#define com_example_ohk1hc_calculatorgui_Calculator_MULTIPLICATION 2L
#undef com_example_ohk1hc_calculatorgui_Calculator_DIVISION
#define com_example_ohk1hc_calculatorgui_Calculator_DIVISION 3L
/*
 * Class:     com_example_ohk1hc_calculatorgui_Calculator
 * Method:    calculate
 * Signature: (FFI)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_ohk1hc_calculatorgui_Calculator_calculate
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     com_example_ohk1hc_calculatorgui_Calculator
 * Method:    stringToId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_ohk1hc_calculatorgui_Calculator_stringToId
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
