/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

#define LOGI(tag, ...) __android_log_print(ANDROID_LOG_INFO, tag, __VA_ARGS__)
#define LOGD(tag, ...) __android_log_print(ANDROID_LOG_DEBUG, tag, __VA_ARGS__)
#define LOGE(tag, ...) __android_log_print(ANDROID_LOG_ERROR, tag, __VA_ARGS__)

/* Header for class com_example_ohk1hc_calculatorgui_Calculator */

#ifndef _Included_com_example_ohk1hc_calculatorgui_Calculator
#define _Included_com_example_ohk1hc_calculatorgui_Calculator
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_ohk1hc_calculatorgui_Calculator
 * Method:    calc
 * Signature: (FFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_ohk1hc_calculatorgui_Calculator_calculate
  (JNIEnv *, jclass, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif

#define SUMMATION 0
#define SUBTRACTION 1
#define MUTIPLICATION 2
#define DIVISION 3

#endif
